[workspace]
members = [
    "ck-pg-client",
]

[workspace.dependencies]
md5 = { version = "~0.7.0" }
rustls = { version = "~0.20.6", default-features = false }
scopeguard = { version = "^1.1.0" }
tempfile = { version = "^3.3.0" }
thiserror = { version = "^1.0.34" }
