[workspace]
members = [
    "ck-pg-client",
]

[workspace.dependencies]
scopeguard = { version = "^1.1.0" }
tempfile = { version = "^3.3.0" }
thiserror = { version = "^1.0.34" }

[workspace.dependencies.rustls]
default-features = false
features = ["dangerous_configuration"]
version = "~0.20.6"
