#!/usr/bin/env bash

set -efuxo pipefail

if ! [[ -e build ]]; then
    mkdir build
    echo '/*' > build/.gitignore
fi

export CARGO_TARGET_DIR=build/cargo

cargo build --features md5,rustls
cargo test --features md5,rustls

cargo build --features rustls
cargo test --features rustls

cargo build --features md5
cargo test --features md5

cargo build
cargo test

cargo doc --all-features
